baseURL = "http://example.com/"
title = "My Blog"
theme = "simple-theme"

languageCode = "ja-jp"
hasCJKLanguage = true

[params]
  description = "A simple Hugo theme based on design-system-example-components-react"
  author = "Author Name"
