baseURL = "https://blog.nexus106.com/"
title = "長文を書くブログ"
theme = "simple-theme"

languageCode = "ja-jp"
hasCJKLanguage = true

# トップページの記事要約の長さ（文字数）
summaryLength = 7

[params]
  description = "長文を書くブログ"
  author = "nexus106"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
